spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jfsjanbatch
    username: root
    password: root
    
#datasource specific properties
  jpa:    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:      ddl-auto: update
      
      